[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "swarmdex-ai"
version = "0.1.0"
requires-python = ">=3.12,<3.15"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)"
]

[tool.poetry.dependencies]
torch = "^2.14.0"
numpy = "^2.5.3"
grpcio = "^1.83.1"
grpcio-tools = "^1.83.1"
protobuf = "^7.36.1"
pyyaml = "^6.0.3"
tensorboard = "^2.21.0"
neuprint-python = "^0.6.3"
pandas = "^2.3.3"
scipy = "^1.17.0"
pyarrow = "^23.0.0"
